//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GhostlyLiveEntities : DbContext
    {
        public GhostlyLiveEntities()
            : base("name=GhostlyLiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ImportProcess> ImportProcesses { get; set; }
        public virtual DbSet<ImportStatu> ImportStatus { get; set; }
        public virtual DbSet<Operator> Operators { get; set; }
        public virtual DbSet<Operators_Locations> Operators_Locations { get; set; }
    }
}
