//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operator()
        {
            this.ImportProcesses = new HashSet<ImportProcess>();
            this.Operators_Locations = new HashSet<Operators_Locations>();
        }
    
        public System.Guid OperatorId { get; set; }
        public string OperatorNameFirm { get; set; }
        public string OperatorVATid { get; set; }
        public string OperatorMainContact { get; set; }
        public string OperatorEmail { get; set; }
        public string OperatorTelephone { get; set; }
        public string OperatorCity { get; set; }
        public string OperatorAddressLine1 { get; set; }
        public string OperatorAddressLine2 { get; set; }
        public string OperatorCountry { get; set; }
        public string OperatorStateOrProvince { get; set; }
        public string OperatorRegion { get; set; }
        public Nullable<int> OperatorCategory { get; set; }
        public Nullable<int> OperatorSubCategory { get; set; }
        public Nullable<int> OperatorGhostlyClassification { get; set; }
        public Nullable<decimal> StorageCapacityLiquids { get; set; }
        public Nullable<decimal> StorageCapacityVolume { get; set; }
        public Nullable<decimal> StorageUsedCapacityLiquids { get; set; }
        public Nullable<decimal> StorageUsedCapacityVolume { get; set; }
        public Nullable<System.Guid> member_id { get; set; }
        public System.DateTime date_creation { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportProcess> ImportProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operators_Locations> Operators_Locations { get; set; }
    }
}
